# Generated by Django 6.0.3 on 2026-04-20 09:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.TextField()),
                ('language_detected', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('hinglish', 'Hinglish')], default='en', max_length=10)),
                ('personality_score', models.FloatField(default=0)),
                ('personality_label', models.CharField(blank=True, max_length=100)),
                ('personality_description', models.TextField(blank=True)),
                ('tone_score', models.FloatField(default=0)),
                ('tone_label', models.CharField(blank=True, max_length=100)),
                ('tone_description', models.TextField(blank=True)),
                ('bias_score', models.FloatField(default=0)),
                ('bias_label', models.CharField(blank=True, max_length=100)),
                ('bias_description', models.TextField(blank=True)),
                ('thinking_score', models.FloatField(default=0)),
                ('thinking_label', models.CharField(blank=True, max_length=100)),
                ('thinking_description', models.TextField(blank=True)),
                ('language_score', models.FloatField(default=0)),
                ('language_label', models.CharField(blank=True, max_length=100)),
                ('language_description', models.TextField(blank=True)),
                ('communication_score', models.FloatField(default=0)),
                ('communication_label', models.CharField(blank=True, max_length=100)),
                ('communication_description', models.TextField(blank=True)),
                ('share_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
