# Generated by Django 6.0.3 on 2026-06-09 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for opponent'), ('thinking', 'Thinking time'), ('active', 'Active'), ('ended', 'Ended'), ('abandoned', 'Abandoned')], default='waiting', max_length=20)),
                ('thinking_seconds', models.IntegerField(default=60)),
                ('thinking_started_at', models.DateTimeField(blank=True, null=True)),
                ('time_per_player_seconds', models.IntegerField(default=180)),
                ('challenger_time_remaining', models.FloatField(blank=True, null=True)),
                ('opponent_time_remaining', models.FloatField(blank=True, null=True)),
                ('turn_started_at', models.DateTimeField(blank=True, null=True)),
                ('current_turn_user_id', models.IntegerField(blank=True, null=True)),
                ('debate_started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('messages', models.JSONField(default=list)),
                ('challenger_argument_strength', models.FloatField(blank=True, null=True)),
                ('challenger_logical_coherence', models.FloatField(blank=True, null=True)),
                ('challenger_rebuttal_quality', models.FloatField(blank=True, null=True)),
                ('challenger_clarity', models.FloatField(blank=True, null=True)),
                ('challenger_composure', models.FloatField(blank=True, null=True)),
                ('challenger_feedback', models.TextField(blank=True)),
                ('opponent_argument_strength', models.FloatField(blank=True, null=True)),
                ('opponent_logical_coherence', models.FloatField(blank=True, null=True)),
                ('opponent_rebuttal_quality', models.FloatField(blank=True, null=True)),
                ('opponent_clarity', models.FloatField(blank=True, null=True)),
                ('opponent_composure', models.FloatField(blank=True, null=True)),
                ('opponent_feedback', models.TextField(blank=True)),
                ('share_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debates_as_challenger', to=settings.AUTH_USER_MODEL)),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debates_as_opponent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
