# Generated by Django 6.0.3 on 2026-06-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='final_turn_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
